### ISSUE TITLE
problem of convergence

### ISSUE THREAD

**Issue by wjczf123** [Determined22/Rank-Emotion-Cause#2]
When I set the seed equals 1, the result F_ ecp is 0.049 in fold-6. And other folds is normal and the average is 0.6588. What is the problem?

**Comment by juli0213** [comment]
Did you run the model successfully? 
I have a bug of 
Token indices sequence length is longer than the specified maximum sequence length for this model (730 > 512). Running this sequence through the model will result in indexing errors
If you solve this please let me know, thank u~

**Comment by juli0213** [comment]
> When I set the seed equals 1, the result F_ ecp is 0.049 in fold-6. And other folds is normal and the average is 0.6588. What is the problem?

Did you run the model successfully?
I have a bug of
Token indices sequence length is longer than the specified maximum sequence length for this model (730 > 512). Running this sequence through the model will result in indexing errors
If you solve this please let me know, thank u~

**Comment by wjczf123** [comment]
I can run this model.
I get warning:
Token indices sequence length is longer than the specified maximum sequence length for this model (730 > 512). Running this sequence through the model will result in indexing errors
Token indices sequence length is longer than the specified maximum sequence length for this model (658 > 512). Running this sequence through the model will result in indexing errors
Token indices sequence length is longer than the specified maximum sequence length for this model (557 > 512). Running this sequence through the model will result in indexing errors
Although there are warnings, the code can run.
